# Generated by Django 3.1.7 on 2021-03-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('quot', models.CharField(max_length=50)),
                ('sent', models.CharField(max_length=20)),
                ('follow', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('atten', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('state', models.CharField(max_length=15)),
                ('statecode', models.CharField(max_length=3)),
                ('address', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=30)),
                ('quotnum', models.CharField(max_length=20)),
                ('quotdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=5)),
                ('unit', models.CharField(max_length=8)),
                ('required', models.CharField(max_length=50)),
                ('refer', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('due', models.IntegerField()),
                ('bill_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('followup', models.CharField(max_length=20)),
                ('stat', models.CharField(max_length=100)),
                ('recieve', models.IntegerField()),
                ('weekno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=5)),
                ('unit', models.CharField(max_length=5)),
                ('rate', models.IntegerField()),
                ('tax', models.CharField(max_length=5)),
                ('signature', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=10)),
            ],
        ),
    ]
