# Generated by Django 3.1.7 on 2021-03-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20210323_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
        migrations.AddField(
            model_name='indent',
            name='status',
            field=models.CharField(default='0000000', editable=False, max_length=10),
        ),
    ]
