# Generated by Django 3.1.7 on 2021-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_indent_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='priority',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='indent',
            name='status',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
    ]
