# Generated by Django 3.1.7 on 2021-03-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20210323_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='week',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='weekno',
            field=models.CharField(default='', max_length=10),
        ),
    ]
