# Generated by Django 3.1.7 on 2021-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20210323_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('revert', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oldclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('revert', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('quotnumber', models.CharField(max_length=50)),
                ('sentdate', models.CharField(max_length=20)),
                ('followupdate', models.IntegerField()),
                ('reply', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('qtnumber', models.CharField(max_length=50)),
                ('contactperson', models.CharField(max_length=20)),
                ('contactno', models.IntegerField()),
                ('reverts', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='indent',
            name='make',
            field=models.CharField(default='', max_length=10),
        ),
    ]
