# Generated by Django 3.1.7 on 2021-03-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_auto_20210323_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newclient',
            old_name='revert',
            new_name='reverted',
        ),
        migrations.RenameField(
            model_name='oldclient',
            old_name='client_name',
            new_name='clientname',
        ),
        migrations.RenameField(
            model_name='oldclient',
            old_name='contact_no',
            new_name='contactno',
        ),
        migrations.RenameField(
            model_name='oldclient',
            old_name='contact_person',
            new_name='contactperson',
        ),
        migrations.RenameField(
            model_name='oldclient',
            old_name='purpose',
            new_name='purposetalk',
        ),
        migrations.RenameField(
            model_name='paymentfollow',
            old_name='client_name',
            new_name='clients',
        ),
        migrations.RenameField(
            model_name='quotationfollow',
            old_name='contactno',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='quotationfollow',
            old_name='contactperson',
            new_name='contactprson',
        ),
        migrations.RenameField(
            model_name='quotationfollow',
            old_name='client_name',
            new_name='grahak',
        ),
    ]
