# Generated by Django 3.1.7 on 2021-03-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20210323_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclient',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='oldclient',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentfollow',
            name='followupdate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationfollow',
            name='contactnumber',
            field=models.CharField(max_length=10),
        ),
    ]
