# Generated by Django 3.1.7 on 2021-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20210323_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfollow',
            name='dueamt',
            field=models.CharField(default='', max_length=10),
        ),
    ]
