# Generated by Django 3.1.7 on 2021-03-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_paymentfollow_dueamt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('client_gst', models.CharField(max_length=20)),
                ('client_state', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('company_add', models.CharField(max_length=50)),
                ('bill_date', models.CharField(max_length=10)),
                ('rgpdate', models.CharField(max_length=10)),
                ('rgpno', models.CharField(max_length=20)),
                ('po_no', models.CharField(max_length=20)),
                ('po_date', models.CharField(max_length=10)),
                ('hsn', models.CharField(max_length=10)),
                ('item_description', models.CharField(max_length=100)),
                ('quantity_item', models.CharField(max_length=10)),
                ('pricing', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
                ('gst', models.CharField(max_length=10)),
            ],
        ),
    ]
