# Generated by Django 3.1.7 on 2021-03-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='po_date',
        ),
    ]
