# Generated by Django 3.1.7 on 2021-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_remove_billing_po_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='po_date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
