# Generated by Django 3.1.7 on 2021-03-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_billing_po_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfollow',
            name='total_balance',
            field=models.CharField(default='', max_length=10),
        ),
    ]
