# Generated by Django 3.1.7 on 2021-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_qty', models.CharField(max_length=10)),
                ('item_image', models.ImageField(default='', upload_to='static/stock')),
            ],
        ),
    ]
