# Generated by Django 3.1.7 on 2021-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_and_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='hsn',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_rate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
