# Generated by Django 3.1.7 on 2021-03-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_and_purchase', '0002_auto_20210324_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchasedby',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='receiveddate',
            field=models.CharField(default='', max_length=10),
        ),
    ]
