# Generated by Django 3.1.7 on 2021-03-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_and_purchase', '0003_auto_20210326_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentInvoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('issuedate', models.DateField()),
                ('po_no', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=5)),
                ('purpose', models.CharField(max_length=20)),
            ],
        ),
    ]
